# Generated by Django 3.0.7 on 2021-05-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_producer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
